name: isolate_worker
description: A brainfuck IsolateWorker.
version: 0.0.1
homepage: https://github.com/brucelandor/isolate_worker
author: libo <brucelandor@gmail.com>

environment:
  sdk: ">=2.5.0 <3.0.0"

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
